spring.application.name=throne-of-consequence

# Server
server.port=8080

# Ollama config
ollama.base-url=http://localhost:11434
ollama.model=qwen2.5:7b-instruct
ollama.keep-alive=30m
#ollama.model=qwen2.5:3b-instruct

# Actuator
management.endpoints.web.exposure.include=health,info